/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Uploader */

#ifndef _Included_Uploader
#define _Included_Uploader
#ifdef __cplusplus
extern "C" {
#endif
#undef Uploader_FOCUS_TRAVERSABLE_UNKNOWN
#define Uploader_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef Uploader_FOCUS_TRAVERSABLE_DEFAULT
#define Uploader_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef Uploader_FOCUS_TRAVERSABLE_SET
#define Uploader_FOCUS_TRAVERSABLE_SET 2L
#undef Uploader_TOP_ALIGNMENT
#define Uploader_TOP_ALIGNMENT 0.0f
#undef Uploader_CENTER_ALIGNMENT
#define Uploader_CENTER_ALIGNMENT 0.5f
#undef Uploader_BOTTOM_ALIGNMENT
#define Uploader_BOTTOM_ALIGNMENT 1.0f
#undef Uploader_LEFT_ALIGNMENT
#define Uploader_LEFT_ALIGNMENT 0.0f
#undef Uploader_RIGHT_ALIGNMENT
#define Uploader_RIGHT_ALIGNMENT 1.0f
#undef Uploader_serialVersionUID
#define Uploader_serialVersionUID -7644114512714619750LL
#undef Uploader_serialVersionUID
#define Uploader_serialVersionUID 4613797578919906343LL
#undef Uploader_INCLUDE_SELF
#define Uploader_INCLUDE_SELF 1L
#undef Uploader_SEARCH_HEAVYWEIGHTS
#define Uploader_SEARCH_HEAVYWEIGHTS 1L
#undef Uploader_serialVersionUID
#define Uploader_serialVersionUID -2728009084054400034LL
#undef Uploader_serialVersionUID
#define Uploader_serialVersionUID -5836846270535785031LL
/*
 * Class:     Uploader
 * Method:    getWoWPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Uploader_getWoWPath
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
